
services:
  gateway:
    image: nginx:1.27.5-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 3000:80
    networks:
      - prod

  front:
    image: ymerzouka/verdant-frontend:latest
    ports:
      - 3001:3000
    depends_on:
      - back
    environment:
      - BACKEND_URL=http://back:8000/api
      - ACCESS_JWT_SECRET="verdant-secret"
      - CELL_ID=beb56e75-b158-4e33-9125-84f0c3b3d618
    networks:
      - prod

  back:
    image: ymerzouka/verdant-backend:latest
    depends_on:
      - db
    environment:
      - BROKER_URL=mqtts://verdant.francecentral-1.ts.eventgrid.azure.net
      - DATABASE_URL=postgresql://verdant:verdant2025@db:5432/verdant_db
      - ACCESS_JWT_SECRET="verdant-secret"
      - REFRESH_JWT_SECRET="another-verdant-secret"
      - NODE_ENV=production
      - MQTT_USERNAME=backend
      - MQTT_ID_PREFIX=backend-prod
    ports:
      - 8000:8000
    networks:
      - prod

  studio:
    image: dpage/pgadmin4:2025-05-27-1
    environment:
      - PGADMIN_DEFAULT_EMAIL=verdant@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Hello2025
    depends_on:
      - db
    ports:
      - 5000:80
    networks:
        - prod

  db:
    image: postgres:latest
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: verdant_db
      POSTGRES_USER: verdant
      POSTGRES_PASSWORD: verdant2025
    ports:
      - "5432:5432"
    networks:
        - prod
    # restart: unless-stopped
networks:
  prod:
volumes:
  db-data:
