# Kubernetes Secret for pgAdmin Password
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  labels:
    app: pgadmin
type: Opaque
data:
  PGADMIN_DEFAULT_PASSWORD: SGVsbG8yMDI1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      initContainers:
      - name: wait-for-db-for-pgadmin
        image: postgres:latest
        command: ['sh', '-c', 'until pg_isready -h db -p 5432 -U verdant; do echo "Waiting for database for pgAdmin..."; sleep 3; done; echo "Database is ready for pgAdmin!"']
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:2025-05-27-1
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "verdant@gmail.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin-secret
              key: PGADMIN_DEFAULT_PASSWORD
        - name: PGADMIN_LISTEN_PORT # Explicitly set, though 80 is default
          value: "80"
        # resources:
        #   requests:
        #     memory: "256Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "1Gi" # pgAdmin can be memory intensive
        #     cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: studio
  labels:
    app: pgadmin
spec:
  type: ClusterIP # Default: Exposes the service on an internal IP in the cluster.
  selector:
    app: pgadmin
  ports:
  - name: http-pgadmin
    protocol: TCP
    port: 80
    targetPort: 80
